[font]
path = "../fonts/NotoSansJP-Regular.ttf"

[input]
chars = ["chars.txt"]
preserve_space = true

[output]
language = "c"
name = "sample_font"
directory = "."
format = "c-fixed"

[generation]
sizes = [26]
alpha_bits = 4
missing_glyphs = "error"

[fixed_cell]
width = 26
height = 26
